/*
 *  This module is just a placeholder for the production template cache module, which is generated by the build:templates task.
 *  goog and angular need the module definition or else will throw errors when the 'templates' module is required/injected in app.js
 *  TODO: there's got to be a more elegant way of doing this
 */

'use strict';
goog.provide('my.templates');
my.templates = angular.module("templates", []);

